#You can replace with your own marketplace & balanced key
development:
  BALANCED_MARKETPLACE: TEST-MP6p48kuwiMNY0CdLoaLSICs
  BALANCED_KEY: ak-test-M1tkCleyBaUFQk0QW2uzXqvEthUAAmI3

test:
  BALANCED_MARKETPLACE: TEST-MP6p48kuwiMNY0CdLoaLSICs
  BALANCED_KEY: ak-test-M1tkCleyBaUFQk0QW2uzXqvEthUAAmI3

production:
  BALANCED_MARKETPLACE: TEST-MP6p48kuwiMNY0CdLoaLSICs
  BALANCED_KEY: ak-test-M1tkCleyBaUFQk0QW2uzXqvEthUAAmI3