#You can replace with your own marketplace & balanced key
development:
  BALANCED_MARKETPLACE: TEST-MP3QqOc001Z7X4pu2NfKv7Zr
  BALANCED_KEY: ak-test-1X7E6OzicTu2VnQg3rUQaV9sQfAFqQj35

test:
  BALANCED_MARKETPLACE: TEST-MP3QqOc001Z7X4pu2NfKv7Zr
  BALANCED_KEY: ak-test-1X7E6OzicTu2VnQg3rUQaV9sQfAFqQj35

production:
  BALANCED_MARKETPLACE: TEST-MP3QqOc001Z7X4pu2NfKv7Zr
  BALANCED_KEY: ak-test-1X7E6OzicTu2VnQg3rUQaV9sQfAFqQj35